recognition:
  face alignment:
    # {mtcnn, dlib, opencv, face-boxes, adas}
    provider: adas

    adas:
      # openvino only, thus we can choose device
      # {myriad, cpu, gpu, hetero}
      device: cpu
      width: 672
      height: 384
      threshold: 0.6
      cpu:
        model: models/adas/FP32/face-detection-adas-0001
        extension library: /opt/intel/computer_vision_sdk/deployment_tools/inference_engine/lib/ubuntu_18.04/intel64/libcpu_extension_avx2.so

  embedding:
    # {tf, openvino}
    framework: tf
    provider: facenet

    tf:
      # uses CUDA gpu automatically by default
      facenet:
        model: models/facenet/TF/20180402-114759.pb
        image size: 160

  classification:
    # {test-classifier, svm-classifier}
    provider: test-classifier
    test-classifier conf:
      model: models/classifier/aligned_raw.pkl
      threshold: 0.35